const PLAYER_START_GAME_ENERGY = 100;
const PLAYER_SPEED = 400;
const PLAYER_HIT_BY_ENEMY_DAMAGE = 10;

const ENEMY_ATTACK_ARC_DEGREES = 45;

const KILL_ENEMY_SCORE = 10;

const HEALTH_POTION_BONUS = 50;

