const PLAYER_START_GAME_ENERGY = 100;
const PLAYER_SPEED = 600;
const PLAYER_FIRE_DELAY = 0.25;
const PLAYER_HIT_BY_ENEMY_DAMAGE = 10;

const ENEMY_MULTIPLIER_AT_WAVE_START = 5;
const ENEMY_MULTIPLIER_DURING_WAVE = 5;
const ENEMY_SPAWN_MINIMUM_SECONDS = 1;
const ENEMY_SPAWN_MAXIMUM_SECONDS = 3;
const ENEMY_SPAWN_MAX_BATCH_SIZE = 5;
const ENEMY_SPEED = 450;
const ENEMY_NECROMANCER_SPEED = 100;

const ENEMY_HEALTH = 1;
const ENEMY_NECROMANCER_HEALTH = 5;

const ENEMY_ATTACK_MINIMUM_SECONDS = 1;
const ENEMY_ATTACK_MAXIMUM_SECONDS = 3;
const ENEMY_ATTACK_ARC_DEGREES = 20;
const ENEMY_NECROMANCER_ATTACK_MINIMUM_SECONDS = 3;
const ENEMY_NECROMANCER_ATTACK_MAXIMUM_SECONDS = 7;

const ENEMY_CHASE_REORIENT_MINIMUM_SECONDS = 0.5;
const ENEMY_CHASE_REORIENT_MAXIMUM_SECONDS = 1.0;
const ENEMY_DEFAULT_CHANGE_DIRECTION_MINIMUM_SECONDS = 1;
const ENEMY_DEFAULT_CHANGE_DIRECTION_MAXIMUM_SECONDS = 3;

const ENEMY_TRAP_MINIMUM_SECONDS = 5;
const ENEMY_TRAP_MAXIMUM_SECONDS = 8;

const KILL_ENEMY_SCORE = 10;

# Fish
const FISH_TO_SPAWN = 10;
const GET_FISH_SCORE = 50;

# Items
const ITEM_SPAWN_MINIMUM_SECONDS = 5;
const ITEM_SPAWN_MAXIMUM_SECONDS = 10;

const HEALTH_POTION_BONUS = 50;
const POWER_UP_ACTIVE_DURATION = 5;

