const PLAYER_START_GAME_ENERGY = 100;
const PLAYER_SPEED = 400;
const PLAYER_FIRE_DELAY = 0.25;
const PLAYER_HIT_BY_ENEMY_DAMAGE = 10;

const ENEMY_SPEED = 400;
const ENEMY_ATTACK_MINIMUM_SECONDS = 1;
const ENEMY_ATTACK_MAXIMUM_SECONDS = 3;
const ENEMY_ATTACK_ARC_DEGREES = 20;

const ENEMY_TRAP_MINIMUM_SECONDS = 5;
const ENEMY_TRAP_MAXIMUM_SECONDS = 8;

const KILL_ENEMY_SCORE = 10;

# Fish
const GET_FISH_SCORE = 50;

# Items
const ITEM_SPAWN_MINIMUM_SECONDS = 5;
const ITEM_SPAWN_MAXIMUM_SECONDS = 10;

const HEALTH_POTION_BONUS = 50;
const POWER_UP_ACTIVE_DURATION = 5;

